/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddEmployeeRouteImport } from './routes/add-employee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees/$employeeId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'

const AddEmployeeRoute = AddEmployeeRouteImport.update({
  id: '/add-employee',
  path: '/add-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-employee': typeof AddEmployeeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-employee': typeof AddEmployeeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-employee': typeof AddEmployeeRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-employee'
    | '/demo/tanstack-query'
    | '/employees/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-employee' | '/demo/tanstack-query' | '/employees/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/add-employee'
    | '/demo/tanstack-query'
    | '/employees/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEmployeeRoute: typeof AddEmployeeRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-employee': {
      id: '/add-employee'
      path: '/add-employee'
      fullPath: '/add-employee'
      preLoaderRoute: typeof AddEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEmployeeRoute: AddEmployeeRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
